version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - ENV=production
    command: uvicorn src.api.main:app --host 0.0.0.0 --port 8000

  dashboard:
    build:
      context: .
      dockerfile: deployment/Dockerfile
    ports:
      - "8501:8501"
    command: streamlit run src/dashboard/streamlit_app.py --server.port 8501 --server.address 0.0.0.0
    depends_on:
      - api
